services:
  - type: web
    name: bday-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: GRIDFS_BUCKET_NAME
        value: photos
